// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm4K7o307nK4wl5atgSZDWgaP_9krXThc',
    appId: '1:53399215816:web:13dc77347f8dcae78ecffd',
    messagingSenderId: '53399215816',
    projectId: 'meyepro-c3f9a',
    authDomain: 'meyepro-c3f9a.firebaseapp.com',
    storageBucket: 'meyepro-c3f9a.appspot.com',
    measurementId: 'G-04QHHEBP7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk2vpM10YsV4BAQB3tZKOaocNvjR7IKS0',
    appId: '1:53399215816:android:25479038f8dfb81f8ecffd',
    messagingSenderId: '53399215816',
    projectId: 'meyepro-c3f9a',
    storageBucket: 'meyepro-c3f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFeCbxTcy5zhm0QV_dLW9pypIM5sRjOXs',
    appId: '1:53399215816:ios:baed3d3694bc5ae98ecffd',
    messagingSenderId: '53399215816',
    projectId: 'meyepro-c3f9a',
    storageBucket: 'meyepro-c3f9a.appspot.com',
    iosClientId: '53399215816-b0qtlgcu1hagn1jf0l04936u0alc6fd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveStreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFeCbxTcy5zhm0QV_dLW9pypIM5sRjOXs',
    appId: '1:53399215816:ios:baed3d3694bc5ae98ecffd',
    messagingSenderId: '53399215816',
    projectId: 'meyepro-c3f9a',
    storageBucket: 'meyepro-c3f9a.appspot.com',
    iosClientId: '53399215816-b0qtlgcu1hagn1jf0l04936u0alc6fd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveStreaming',
  );
}
